wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 3
      4: 3.6.12
      5: 0.10.25
      8:
      - 5
